language: bash

sudo: required

services: [docker]

script:
  - docker run --network=host -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft:beta sh -c "apt update && snapcraft"
  - sudo apt update
  - sudo apt install --yes snapd
  - sudo snap install *.snap --classic --dangerous
  - sudo pip install -U pytest
  - pwd
  - ps -ef
  - ls -l
  - ./tests/smoke-test.sh
  - export UNDER_TIME_PRESURE="True"
  - (cd tests; pytest -s verify-branches.py)
  - (cd tests; pytest -s test-addons.py)
  - sudo microk8s.reset
  - sudo snap remove microk8s
  - UPGRADE_MICROK8S_FROM=edge UPGRADE_MICROK8S_TO=`pwd`/`ls microk8s*.snap` pytest -s ./tests/test-upgrade.py
