dist: xenial
language: bash
sudo: required

addons:
  snaps:
   - name: snapcraft
     channel: stable
     confinement: classic
   - name: lxd
     channel: stable
  apt:
    packages:
      - python3  
      - python3-pip   

script:
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sudo snapcraft --use-lxd
  - sudo apt update
  - sudo snap install *.snap --classic --dangerous
  - sudo pip3 install --upgrade pip
  - sudo pip3 install -U pytest
  - pwd
  - ps -ef
  - ls -l
  - ./tests/smoke-test.sh
  - export UNDER_TIME_PRESSURE="True"
  - (cd tests; pytest -s verify-branches.py)
  - (cd tests; sudo -E pytest -s -ra test-addons.py)
  - sudo microk8s.reset
  - sudo snap remove microk8s
# There is no upgrade path for now we are going to a new epoch. We should reenable thi after the first release.
#  - sudo -E UPGRADE_MICROK8S_FROM=edge UPGRADE_MICROK8S_TO=`pwd`/`ls microk8s*.snap` pytest -s ./tests/test-upgrade.py
