image: Visual Studio 2019
environment:
  INNOCC: C:\Program Files (x86)\Inno Setup 6\iscc.exe
  MAKEAPPX: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\makeappx.exe
  SIGNTOOL: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe
  MICROK8S_INSTALLED_EXE: C:\Program Files (x86)\MicroK8s for Windows\microk8s.exe

  matrix:
  - PYTHON: C:\Python37-x64

clone_depth: 1
cache:
- '%LOCALAPPDATA%\pip\Cache\http'
- '%LOCALAPPDATA%\pip\Cache\wheels'
build: off

install:
- cmd: |
    %PYTHON%\python.exe -m venv venv
    venv\Scripts\activate.bat
    %PYTHON%\python.exe -c "import sys; print(sys.executable)"
    %PYTHON%\python.exe -m pip install -r installer\requirements.txt
    %PYTHON%\python.exe -m pip install pyinstaller
    venv\Scripts\deactivate.bat

build_script:
- cmd: |
    venv\Scripts\activate.bat
    cd installer
    echo "Building microk8s.exe..."
    pyinstaller.exe --onefile microk8s.spec
    ..\venv\Scripts\deactivate.bat

    echo "Test signing microk8s.exe..."
    powershell.exe windows\generate-self-signed-cert.ps1
    "%SIGNTOOL%" sign /fd SHA256 /T "http://timestamp.verisign.com/scripts/timstamp.dll" /F test-signing.pfx /P Password1234 dist\microk8s.exe

    echo "Building microk8s inno installer..."
    "%INNOCC%" windows\microk8s.iss

    echo "Test signing microk8s inno installer..."
    "%SIGNTOOL%" sign /fd SHA256 /T "http://timestamp.verisign.com/scripts/timstamp.dll" /F test-signing.pfx /P Password1234 dist\microk8s-installer.exe

    echo "Building microk8s msix installer..."
    mkdir dist\msix
    copy dist\microk8s.exe dist\msix\
    copy windows\microk8s.png dist\msix\
    copy windows\AppxManifest.xml dist\msix\
    "%MAKEAPPX%" pack /h SHA256 /d dist\msix /p dist\microk8s-installer.msix

    echo "Test signing microk8s msix installer..."
    "%SIGNTOOL%" sign /fd SHA256 /T "http://timestamp.verisign.com/scripts/timstamp.dll" /F test-signing.pfx /P Password1234 dist\microk8s-installer.msix

    cd ..

test_script:
- cmd: |
    echo "Running select unit tests..."

artifacts:
- path: installer\dist\microk8s.exe
- path: installer\dist\microk8s-installer.exe
- path: installer\dist\microk8s-installer.msix