name: Build MicroK8s Installers

on:
  push:
    branches:
      - "**install**"
  pull_request:
    branches:
      - "**install**"

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/installer/windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.8
      - name: Install Python requirements
        run: python -m pip install -r ../requirements.txt
      - name: Build exe
        working-directory: ${{ github.workspace }}/installer
        run: pyinstaller.exe ./microk8s.spec
      - name: Move exe to installer build directory
        working-directory: ${{ github.workspace }}/installer
        run: move microk8s.exe ./windows/microk8s.exe
      - name: Download EnVar plugin for NSIS
        uses: carlosperate/download-file-action@v2.0.1
        with:
          file-url: https://github.com/GsNSIS/EnVar/releases/download/v0.3.1/EnVar-Plugin.zip
          file-name: envar_plugin.zip
          location: ${{ github.workspace }}
      - name: Extract EnVar plugin
        run: 7z x -o"C:/Program Files (x86)/NSIS" "${{ github.workspace }}/envar_plugin.zip"
      - name: Download Multipass installer
        uses: carlosperate/download-file-action@v2.0.1
        with:
          file-url: https://github.com/canonical/multipass/releases/download/v1.12.2/multipass-1.12.2+win-win64.exe
          file-name: multipass.exe
          location: ${{ github.workspace }}/installer/windows
      - name: Download kubectl
        uses: carlosperate/download-file-action@v2.0.1
        with:
          file-url: https://storage.googleapis.com/kubernetes-release/release/v1.28.3/bin/windows/amd64/kubectl.exe
          file-name: kubectl.exe
          location: ${{ github.workspace }}/installer/windows
      - name: Create installer
        run: makensis.exe ${{ github.workspace }}/installer/windows/microk8s.nsi
      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: Windows installer
          path: ${{ github.workspace }}/installer/windows/microk8s-installer.exe
