name: Build MicroK8s Installers

on:
  push:
    branches:
      - '**install**'
  pull_request:
    branches:
      - '**install**'

jobs:
  windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/installer/windows
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python requirements
      run: python -m pip install -r ../requirements.txt
    - name: Build exe
      run: pyinstaller.exe --onefile ../microk8s.spec
    - name: Download EnVar plugin for NSIS
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://nsis.sourceforge.io/mediawiki/images/7/7f/EnVar_plugin.zip
        file-name: envar_plugin.zip
        location: ${{ github.workspace }}
    - name: Extract EnVar plugin
      #run: 7z x -o"${{ github.workspace }}/NSIS_Plugins" "${{ github.workspace }}/envar_plugin.zip"
      run: 7z x -o"C:/Program Files (x86)/NSIS" "${{ github.workspace }}/envar_plugin.zip"
    - name: Download Multipass installer
      uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: https://people.canonical.com/~msawicz/multipass/v1.2.1/multipass-1.2.1+win-win64.exe
        file-name: multipass.exe
        location: ${{ github.workspace }}/installer/windows
    - name: Debug
      run: |
        cd "C:\Program Files (x86)\NSIS"
        dir
        cd "C:\Program Files (x86)\NSIS\Plugins"
        dir
        cd "C:\Program Files (x86)\NSIS\Contrib"
        dir
        cd "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"
        dir
    - name: Create installer
      run: makensis.exe ${{ github.workspace }}/installer/windows/microk8s.nsi
    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: Windows installer
        path: ${{ github.workspace }}/installer/windows/microk8s-installer.exe
