name: Lint Code

on:
  - push
  - pull_request

jobs:
  build:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: |
          sudo apt-get install tox
          sudo snap install node --classic
          sudo npm install --save-dev --save-exact -g prettier
      - name: Check Python formatting
        run: |
          tox -e lint
      - name: Check YAML formatting
        run: |
          set -eux
          prettier --check $(find . -name "*.yaml" -o -name "*.yml" | \
            grep -v "./microk8s-resources/actions/ingress.yaml" | grep -v "./microk8s-resources/actions/metallb.yaml")
