name: Unit Tests

on:
  - pull_request

jobs:
  check-unit-tests:
    name: Check Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install tox --fix-missing
          sudo pip3 install -U pytest sh
      - name: Check Units
        run: |
          tox -e scripts
          tox -e wrappers
          tox -e cluster
      - name: Verify branches
        run: |
          pytest -s ./tests/verify-branches.py
