name: Lint Code

on:
  - push
  - pull_request

jobs:
  check-formatting:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Install Python
        uses: actions/setup-python@v2

      - name: Check Python linter
        run: |
          python3 -m pip install tox
          tox -e lint

      - name: Install NPM
        uses: actions/setup-node@v2

      - name: Check YAML formatting
        run: |
          set -eux
          npm install --save-dev --save-exact -g prettier
          prettier --check $(find . -name "*.yaml" -o -name "*.yml" | \
            grep -v "./microk8s-resources/actions/ingress.yaml" | \
            grep -v "./microk8s-resources/actions/metallb.yaml" | \
            grep -v invalid.yaml | \
            grep -v calico)
